#pragma once
#include "Components/Position.hpp"
#include "Components/Sprite.hpp"
#include "Components/ScreenPosition.hpp"
#include "Components/RectangleShape.hpp"
#include "Components/Animation.hpp"
#include "Components/Text.hpp"
#include "Components/RemoveAfterDelay.hpp"
#include "Components/Checkbox.hpp"